#ifndef EVENTTYPE_HPP
#define EVENTTYPE_HPP

namespace dblk
{
enum class EventType
{
    NEW_GAME, MOVE, PASS, PASS_TURN, SELECT, SQUARE_LEFT_CLICKED, SQUARE_RIGHT_CLICKED
};
}

#endif // EVENTTYPE_HPP
